// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionExplorer.KMS.Infrastructure.Data;

#nullable disable

namespace SolutionExplorer.KMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227100105_PeriodicQCBaseInfo")]
    partial class PeriodicQCBaseInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SignatureId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SignatureId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AttachmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FileCategory")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("AttachmentFiles");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Documents.DocumentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmerOneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmerOneSignImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmerTwoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmerTwoSignImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("DocumentInfos");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EquipmentModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<int>("IdentifierId")
                        .HasColumnType("int");

                    b.Property<string>("ManufactureCountry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("IdentifierId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("ExecutedScript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<int>("IdentifierId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("IdentifierId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Identifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttachmentFileId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EditNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<int>("IdentifierType")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProducerUserId")
                        .HasColumnType("int");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentFileId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("ProducerUserId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.LabReportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReporterComment")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("int");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("LabReportHistories");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQCAppearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodicQualityControlId")
                        .HasColumnType("int");

                    b.Property<int>("QCBaseInfoAppearanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PeriodicQualityControlId");

                    b.HasIndex("QCBaseInfoAppearanceId");

                    b.ToTable("PeriodicQCAppearances");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQCPhysicalSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodicQualityControlId")
                        .HasColumnType("int");

                    b.Property<int>("QCBaseInfoPhysicalSpecificationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PeriodicQualityControlId");

                    b.HasIndex("QCBaseInfoPhysicalSpecificationId");

                    b.ToTable("PeriodicQCPhysicalSpecifications");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQualityControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoclaveConditions")
                        .HasColumnType("int");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraAutoclaveCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManufacturerCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediumCount")
                        .HasColumnType("int");

                    b.Property<int>("MediumType")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<float>("PowderGramPerLiter")
                        .HasColumnType("real");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlBaseInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("QualityControlDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlPeriod")
                        .HasColumnType("int");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<int>("ShelfLifeDuration")
                        .HasColumnType("int");

                    b.Property<int>("StorageTemperature")
                        .HasColumnType("int");

                    b.Property<string>("UsageStartAcceptanceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("QualityControlBaseInfoId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("PeriodicQualityControls");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PersonnelColorBlindnessTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BlueColorDetection")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<bool>("RedColorDetection")
                        .HasColumnType("bit");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("YellowColorDetection")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("PersonnelColorBlindnessTests");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PersonnelTrainingCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateOfEvent")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<int>("QualificationCriteria")
                        .HasColumnType("int");

                    b.Property<int>("ScoreEarned")
                        .HasColumnType("int");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.ToTable("PersonnelTrainingCourses");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PhysicalSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QCBaseInfoPhysicalSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("QualityControlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("QCBaseInfoPhysicalSpecificationId");

                    b.HasIndex("QualityControlId");

                    b.ToTable("PhysicalSpecifications");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoAppearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppearanceGroup")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlBaseInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("QualityControlBaseInfoId");

                    b.ToTable("QCBaseInfoAppearances");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoExpectedResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ATCCControlOrganism")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExpectedResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaloDiameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoliGroup_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliGroup_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliGroup_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliGroup_D")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QualityControlBaseInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("QualityControlBaseInfoId");

                    b.ToTable("QCBaseInfoExpectedResults");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoPhysicalSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlBaseInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("QualityControlBaseInfoId");

                    b.ToTable("QCBaseInfoPhysicalSpecifications");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Produces")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlBaseInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SampleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageConditionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("QualityControlBaseInfoId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.HasIndex("StorageConditionId");

                    b.ToTable("QualityControls");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DayIntervalCount")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextQualityControlTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("QualityControlBaseInfos");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControlResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectiveActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QCBaseInfoExpectedResultId")
                        .HasColumnType("int");

                    b.Property<int>("QualityControlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("QCBaseInfoExpectedResultId");

                    b.HasIndex("QualityControlId");

                    b.ToTable("QualityControlResults");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentFileId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentifierId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentFileId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IdentifierId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.StorageCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityControlBaseInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("QualityControlBaseInfoId");

                    b.ToTable("StorageConditions");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Personnel", b =>
                {
                    b.HasBaseType("SolutionExplorer.KMS.Domain.Entities.AAA.User");

                    b.Property<int>("EducationalDegree")
                        .HasColumnType("int");

                    b.Property<string>("EducationalField")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirstConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationalChart")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Prefix")
                        .HasColumnType("int");

                    b.Property<int>("SecondConfirmerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SuccessorUserId")
                        .HasColumnType("int");

                    b.HasIndex("FirstConfirmerUserId");

                    b.HasIndex("SecondConfirmerUserId");

                    b.HasIndex("SuccessorUserId");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.Role", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.User", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AttachmentFile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AttachmentFile", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Profile");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.UserRole", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AttachmentFile", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Documents.DocumentInfo", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("Identifier");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.EventLog", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Experiment", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("Identifier");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Identifier", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AttachmentFile", "AttachmentFile")
                        .WithMany()
                        .HasForeignKey("AttachmentFileId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ProducerUser")
                        .WithMany()
                        .HasForeignKey("ProducerUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttachmentFile");

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("ProducerUser");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.LabReportHistory", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("ReceiverUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQCAppearance", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.PeriodicQualityControl", "PeriodicQualityControl")
                        .WithMany("Appearances")
                        .HasForeignKey("PeriodicQualityControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoAppearance", "QCBaseInfoAppearance")
                        .WithMany("PeriodicQCAppearances")
                        .HasForeignKey("QCBaseInfoAppearanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("PeriodicQualityControl");

                    b.Navigation("QCBaseInfoAppearance");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQCPhysicalSpecification", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.PeriodicQualityControl", "PeriodicQualityControl")
                        .WithMany("PhysicalSpecifications")
                        .HasForeignKey("PeriodicQualityControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoPhysicalSpecification", "QCBaseInfoPhysicalSpecification")
                        .WithMany()
                        .HasForeignKey("QCBaseInfoPhysicalSpecificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("PeriodicQualityControl");

                    b.Navigation("QCBaseInfoPhysicalSpecification");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQualityControl", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", "QualityControlBaseInfo")
                        .WithMany()
                        .HasForeignKey("QualityControlBaseInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("PerformedByUser");

                    b.Navigation("QualityControlBaseInfo");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PersonnelColorBlindnessTest", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Personnel");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PersonnelTrainingCourse", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Personnel");

                    b.Navigation("SecondConfirmerUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PhysicalSpecification", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoPhysicalSpecification", "QCBaseInfoPhysicalSpecification")
                        .WithMany()
                        .HasForeignKey("QCBaseInfoPhysicalSpecificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControl", "QualityControl")
                        .WithMany("PhysicalSpecifications")
                        .HasForeignKey("QualityControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("QCBaseInfoPhysicalSpecification");

                    b.Navigation("QualityControl");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoAppearance", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", "QualityControlBaseInfo")
                        .WithMany()
                        .HasForeignKey("QualityControlBaseInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("QualityControlBaseInfo");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoExpectedResult", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", "QualityControlBaseInfo")
                        .WithMany("QCBaseInfoExpectedResults")
                        .HasForeignKey("QualityControlBaseInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("QualityControlBaseInfo");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoPhysicalSpecification", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", "QualityControlBaseInfo")
                        .WithMany("QCBaseInfoPhysicalSpecifications")
                        .HasForeignKey("QualityControlBaseInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("QualityControlBaseInfo");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControl", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", "QualityControlBaseInfo")
                        .WithMany()
                        .HasForeignKey("QualityControlBaseInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.StorageCondition", "StorageCondition")
                        .WithMany()
                        .HasForeignKey("StorageConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("PerformedByUser");

                    b.Navigation("QualityControlBaseInfo");

                    b.Navigation("SecondConfirmerUser");

                    b.Navigation("StorageCondition");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControlResult", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoExpectedResult", "QCBaseInfoExpectedResult")
                        .WithMany()
                        .HasForeignKey("QCBaseInfoExpectedResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControl", "QualityControl")
                        .WithMany("QualityControlResults")
                        .HasForeignKey("QualityControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("QCBaseInfoExpectedResult");

                    b.Navigation("QualityControl");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Reference", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AttachmentFile", "AttachmentFile")
                        .WithMany()
                        .HasForeignKey("AttachmentFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("AttachmentFile");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Identifier");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.StorageCondition", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", "QualityControlBaseInfo")
                        .WithMany("StorageConditions")
                        .HasForeignKey("QualityControlBaseInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("QualityControlBaseInfo");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.SystemSetting", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.Personnel", b =>
                {
                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "FirstConfirmerUser")
                        .WithMany()
                        .HasForeignKey("FirstConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", null)
                        .WithOne()
                        .HasForeignKey("SolutionExplorer.KMS.Domain.Entities.Personnel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SecondConfirmerUser")
                        .WithMany()
                        .HasForeignKey("SecondConfirmerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionExplorer.KMS.Domain.Entities.AAA.User", "SuccessorUser")
                        .WithMany()
                        .HasForeignKey("SuccessorUserId");

                    b.Navigation("FirstConfirmerUser");

                    b.Navigation("SecondConfirmerUser");

                    b.Navigation("SuccessorUser");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.AAA.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.PeriodicQualityControl", b =>
                {
                    b.Navigation("Appearances");

                    b.Navigation("PhysicalSpecifications");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QCBaseInfoAppearance", b =>
                {
                    b.Navigation("PeriodicQCAppearances");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControl", b =>
                {
                    b.Navigation("PhysicalSpecifications");

                    b.Navigation("QualityControlResults");
                });

            modelBuilder.Entity("SolutionExplorer.KMS.Domain.Entities.QualityControlBaseInfo", b =>
                {
                    b.Navigation("QCBaseInfoExpectedResults");

                    b.Navigation("QCBaseInfoPhysicalSpecifications");

                    b.Navigation("StorageConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
